config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#index'
  resources :companies, only: [:show], param: :name, path: '' do
    resources :departments, only: [:index, :show]
    resources :employees, except: [:edit, :new, :update] do
      member do
        get 'edit_information', to: 'employees#edit_information'
        get 'edit_compensation', to: 'employees#edit_compensation'
        patch 'update_information', to: 'employees#update_information'
        patch 'update_compensation', to: 'employees#update_compensation'
      end
    end
  end
  post 'login', to: 'sessions#login'
  post 'logout', to: 'sessions#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :departments
  has_many :employees, through: :departments

  validates :company_name, presence: true, uniqueness: true

  def to_param
    company_name
  end

  def top_three_earners_by_department
    sql = <<-SQL
      SELECT id, name, salary, department_id, department_name, company_id
      FROM (
        SELECT employees.id id, name, department_id, department_name, salary, company_id, RANK() 
          OVER (PARTITION BY department_id 
                ORDER BY department_name, salary DESC) 
          AS rank 
        FROM employees 
        INNER JOIN departments ON employees.department_id = departments.id 
        INNER JOIN companies ON companies.id = departments.company_id 
        WHERE company_id = #{id}) 
      WHERE rank <= 3
    SQL
    Employee.find_by_sql(sql)
  end

end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
  belongs_to :company

  validates :department_name, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department

  validates :name, :title, :email, :salary, presence: true

  def company
    department.company
  end

  # We use this to populate the sign in select box.
  def name_company_role
    "#{name} - #{company.company_name} #{' (Administrator) ' if admin? }"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :current_company
  before_action :employee_list

  private

  def authenticate_user
    return if current_user&.company == current_company
    flash[:alert] = "You need to authenticate first."
    redirect_to root_path
  end

  def authenticate_admin
    return if current_user&.admin && current_user.company == current_company
    flash[:alert] = "You need to be an administrator to access this page."
    if current_user&.company == current_company
      redirect_to company_employee_path(current_company, current_user)
    else
      redirect_to root_path
    end
  end

  def current_user
    Employee.find_by(id: session[:user])
  end

  def current_company
    company = params[:company_name] || params[:name]
    Company.find_by(company_name: company)
  end

  def employee_list
    if current_company
      @employees = current_company.employees
    else
      @employees = Employee.all
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_admin

  def show
    @company = current_company
    @top_earners = @company.top_three_earners_by_department
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_admin
  before_action :verify_access, only: :show

  def index
    @departments = current_company.departments
  end

  def show
    @department = Department.find_by(id: params[:id])
    @employees = @department.employees.order(salary: :desc)
  end

  private

  def verify_access
    return if current_company.departments.include? Department.find_by(id: params[:id])
    flash[:alert] = "You need to be an administrator of this company to access this page"
    redirect_to root_path
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user
  before_action :authenticate_admin, except: [:show, :edit_information, :update_information]
  before_action :verify_access, except: :index

  def index
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit_information
    @employee = Employee.find(params[:id])
  end

  def edit_compensation
    @employee = Employee.find(params[:id])
  end

  def update_information
    @employee = Employee.find(params[:id])
    if @employee.update(personal_params)
      flash[:success] = "Personal information updated successfully"
      redirect_to company_employee_path(current_company.company_name, @employee)
    else
      flash[:alert] = @employee.errors.full_messages.to_sentence
      redirect_to edit_information_company_employee_path(current_company.company_name, @employee)
    end
  end

  def update_compensation
    @employee = Employee.find(params[:id])
    if @employee.update(compensation_params)
      flash[:success] = "Compensation information updated successfully"
      redirect_to company_employee_path(current_company.company_name, @employee)
    else
      flash[:alert] = @employee.errors.full_messages.to_sentence
      redirect_to edit_compensation_company_employee_path(current_company.company_name, @employee)
    end
  end

  private

  def verify_access
    employee = Employee.find(params[:id])
    # If the user is the same OR if the user is an administrator for the company THEN allow access.
    return if (current_user == employee || (current_user.admin && current_user.company == employee.company))
    flash[:alert] = "You need to be an administrator of this company to access this page"
    redirect_to root_path
  end

  def personal_params
    params.require(:employee).permit(:email, :address, :phone)
  end

  def compensation_params
    params.require(:employee).permit(:salary, :bonus, :health_insurance, :matching, :pto)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
  end

  def login
    user = Employee.find(params[:employee])
    session[:user] = user.id
    redirect_to user.admin ? company_path(user.company) : company_employee_path(user.company, user)
  end

  def logout
    session[:user] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      else "alert alert-warning"
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/companies/show.html.erb
<h3><%= @company.company_name %></h3>
<p><%= @company.sector %></p>
<p><%= @company.address %></p>
<p><%= @company.phone %></p>

<%= link_to "View all employees", company_employees_path(@company), class: "btn btn-info" if current_user.admin %>
<%= link_to "View your information", company_employee_path(@company, current_user), class: "btn btn-info" %>
<%= link_to "View all departments", company_departments_path(@company), class: "btn btn-info" %>
<br><br>

<table class="table col-sm-4 table-bordered table-hover table-sm">
  <tr class="table-active">
    <th scope="col">Department</th>
    <th scope="col">Name</th>
    <th scope="col">Top Salaries</th>
  </tr>
  <% @top_earners.each do |employee| %>
    <tr>
      <td><%= link_to employee.department_name, company_department_path(current_company, employee.department_id) %></td>
      <td><%= link_to(employee.name, company_employee_path(@company.company_name, employee.id)) %></td>
      <td><%= employee.salary %></td>
    </tr>
  <% end %>
</table>

app/views/departments/index.html.erb
<h3>Departments of <%= current_company.company_name %></h3>
<ul>
  <% @departments.each do |department| %>
    <li><%= link_to department.department_name, company_department_path(current_company, department) %></li>
  <% end %>
</ul>

app/views/departments/show.html.erb
<h3><%= @department.department_name %></h3>

<table class="table col-sm-4 table-bordered table-hover table-sm">
  <tr class="table-active">
    <th scope="col">Name</th>
    <th scope="col">Salary</th>
  </tr>
  <% @employees.each do |employee| %>
    <tr>
      <td><%= link_to(employee.name, company_employee_path(current_company.company_name, employee.id)) %></td>
      <td><%= employee.salary %></td>
    </tr>
  <% end %>
</table>

app/views/employees/edit_compensation.html.erb
<div class="col-sm-4">
  <%= form_for(@employee, url: { action: 'update_compensation' }) do |f| %>
    <div class="form-group">
      <%= f.label :salary %>
      <%= f.text_field :salary, value: @employee.salary, class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :bonus %>
      <%= f.text_field :bonus, value: @employee.bonus, class: 'form-control' %>
    </div>
    <div class="form-check">
      <%= f.check_box :health_insurance, value: @employee.health_insurance, class: 'form-check-input' %>
      <%= f.label :pto, class: 'form-check-label' %>
    </div>
    <div class="form-check">
      <%= f.check_box :matching, value: @employee.matching, class: 'form-check-input' %>
      <%= f.label :matching, "401k Matching", class: 'form-check-label' %>
    </div>
    <div class="form-check">
      <%= f.check_box :pto, value: @employee.pto, class: 'form-check-input' %>
      <%= f.label :pto, class: 'form-check-label' %>
    </div>
    <br>
    <%= f.submit :Save, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/employees/edit_information.html.erb
<div class="col-sm-4">
  <%= form_for(@employee, url: { action: 'update_information' }) do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, value: @employee.email, class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, value: @employee.address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :phone %>
      <%= f.text_field :phone, value: @employee.phone, class: 'form-control' %>
    </div>
    <br>
    <%= f.submit :Save, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/employees/index.html.erb
<h3> <%= current_company.company_name %> employee list</h3>
<br>
<% @employees.each do |employee| %>
  <p>
    <%= link_to(employee.name, company_employee_path(current_company, employee)) %>
  </p>
<% end %>

app/views/employees/show.html.erb
<p>Name: <%= @employee.name %></p>
<p>Title: <%= @employee.title %></p>
<p>Email: <%= @employee.email %></p>
<p>Address: <%= @employee.address %></p>
<p>Phone: <%= @employee.phone %></p>
<p>Salary: <%= @employee.salary %></p>
<p>Bonus: <%= @employee.bonus %></p>
<p>Health Insurance: <%= @employee.health_insurance ? "Yes" : "No" %></p>
<p>401k Matching: <%= @employee.matching ? "Yes" : "No" %></p>
<p>PTO: <%= @employee.pto ? "Yes" : "No" %></p>

<%= link_to('Edit personal information', edit_information_company_employee_path(current_company.company_name, @employee), class: "btn btn-info") if current_user == @employee || current_user.admin %>
<%= link_to('Edit compensation information', edit_compensation_company_employee_path(current_company.company_name, @employee), class: "btn btn-info") if current_user.admin %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> alert-dismissible fade show col-sm-4">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_header.html.erb
 <nav class="row navbar navbar-expand-lg navbar-light bg-light">
   <div class="col-sm-4">
     <%=link_to("Employee Manager App", logout_path, method: :post)  %> |
     <%=link_to(current_company.company_name.titleize, company_path(current_company.company_name)) if current_company %>
   </div>
   <div class="col-sm-4">
     <% if current_user %>
       Currently logged in as <%= "#{current_user.name} (#{current_user.admin ? 'Admin' : 'Employee'})" %>
       <%= link_to "Log out", logout_path, method: :post %>
     <% end  %>
   </div>
   <div class="col-sm-4">
     <%= form_tag(login_path, authenticity_token: true) do %>
        <div class="form-row align-items-center">
          <%= label_tag('sign_in', 'Sign in as', class: 'col-form-label') %>
          <div class="col-sm-8">
            <%= select_tag('employee', options_from_collection_for_select(@employees, "id", "name_company_role"), class: "form-control") %>
          </div>
          <div class="col">
            <%= submit_tag('Sign in', class: "btn btn-dark")%>
          </div>
        </div>
     <% end %>
   </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/flash' %>
    <%= yield %>
  </body>
</html>